#############################################################################
# Makefile for building: sgreader
# Generated by qmake (2.01a) (Qt 4.8.4) on: Wed May 29 01:18:54 2013
# Project:  sgreader.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile sgreader.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Igui -Ibuild/moc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/aboutdialog.cpp \
		src/imagetreeitem.cpp \
		src/licencedialog.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/sgbitmap.cpp \
		src/sgfile.cpp \
		src/sgimage.cpp \
		src/gui/filelistpage.cpp \
		src/gui/inputdirpage.cpp \
		src/gui/outputdirpage.cpp \
		src/gui/progresspage.cpp \
		src/gui/extractthread.cpp \
		src/gui/extractwizard.cpp build/moc/moc_mainwindow.cpp \
		build/moc/moc_inputdirpage.cpp \
		build/moc/moc_outputdirpage.cpp \
		build/moc/moc_progresspage.cpp \
		build/moc/moc_extractthread.cpp \
		build/moc/moc_extractwizard.cpp \
		build/rcc/qrc_sgreader.cpp
OBJECTS       = build/obj/aboutdialog.o \
		build/obj/imagetreeitem.o \
		build/obj/licencedialog.o \
		build/obj/main.o \
		build/obj/mainwindow.o \
		build/obj/sgbitmap.o \
		build/obj/sgfile.o \
		build/obj/sgimage.o \
		build/obj/filelistpage.o \
		build/obj/inputdirpage.o \
		build/obj/outputdirpage.o \
		build/obj/progresspage.o \
		build/obj/extractthread.o \
		build/obj/extractwizard.o \
		build/obj/moc_mainwindow.o \
		build/obj/moc_inputdirpage.o \
		build/obj/moc_outputdirpage.o \
		build/obj/moc_progresspage.o \
		build/obj/moc_extractthread.o \
		build/obj/moc_extractwizard.o \
		build/obj/qrc_sgreader.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		sgreader.pro
QMAKE_TARGET  = sgreader
DESTDIR       = 
TARGET        = sgreader

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sgreader.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile sgreader.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile sgreader.pro

dist: 
	@$(CHK_DIR_EXISTS) build/obj/sgreader1.0.0 || $(MKDIR) build/obj/sgreader1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/obj/sgreader1.0.0/ && $(COPY_FILE) --parents src/aboutdialog.h src/imagetreeitem.h src/licencedialog.h src/mainwindow.h src/sgbitmap.h src/sgfile.h src/sgimage.h src/gui/filelistpage.h src/gui/inputdirpage.h src/gui/outputdirpage.h src/gui/progresspage.h src/gui/extractthread.h src/gui/extractwizard.h build/obj/sgreader1.0.0/ && $(COPY_FILE) --parents sgreader.qrc build/obj/sgreader1.0.0/ && $(COPY_FILE) --parents src/aboutdialog.cpp src/imagetreeitem.cpp src/licencedialog.cpp src/main.cpp src/mainwindow.cpp src/sgbitmap.cpp src/sgfile.cpp src/sgimage.cpp src/gui/filelistpage.cpp src/gui/inputdirpage.cpp src/gui/outputdirpage.cpp src/gui/progresspage.cpp src/gui/extractthread.cpp src/gui/extractwizard.cpp build/obj/sgreader1.0.0/ && (cd `dirname build/obj/sgreader1.0.0` && $(TAR) sgreader1.0.0.tar sgreader1.0.0 && $(COMPRESS) sgreader1.0.0.tar) && $(MOVE) `dirname build/obj/sgreader1.0.0`/sgreader1.0.0.tar.gz . && $(DEL_FILE) -r build/obj/sgreader1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp build/moc/moc_inputdirpage.cpp build/moc/moc_outputdirpage.cpp build/moc/moc_progresspage.cpp build/moc/moc_extractthread.cpp build/moc/moc_extractwizard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp build/moc/moc_inputdirpage.cpp build/moc/moc_outputdirpage.cpp build/moc/moc_progresspage.cpp build/moc/moc_extractthread.cpp build/moc/moc_extractwizard.cpp
build/moc/moc_mainwindow.cpp: src/sgfile.h \
		src/sgimage.h \
		src/sgbitmap.h \
		src/mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o build/moc/moc_mainwindow.cpp

build/moc/moc_inputdirpage.cpp: src/gui/inputdirpage.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/inputdirpage.h -o build/moc/moc_inputdirpage.cpp

build/moc/moc_outputdirpage.cpp: src/gui/outputdirpage.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/outputdirpage.h -o build/moc/moc_outputdirpage.cpp

build/moc/moc_progresspage.cpp: src/gui/progresspage.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/progresspage.h -o build/moc/moc_progresspage.cpp

build/moc/moc_extractthread.cpp: src/gui/extractthread.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/extractthread.h -o build/moc/moc_extractthread.cpp

build/moc/moc_extractwizard.cpp: src/gui/extractwizard.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/extractwizard.h -o build/moc/moc_extractwizard.cpp

compiler_rcc_make_all: build/rcc/qrc_sgreader.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_sgreader.cpp
build/rcc/qrc_sgreader.cpp: sgreader.qrc \
		icons/sgreader.png
	/usr/lib/qt4/bin/rcc -name sgreader sgreader.qrc -o build/rcc/qrc_sgreader.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/obj/aboutdialog.o: src/aboutdialog.cpp src/aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/aboutdialog.o src/aboutdialog.cpp

build/obj/imagetreeitem.o: src/imagetreeitem.cpp src/imagetreeitem.h \
		src/sgimage.h \
		src/sgbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/imagetreeitem.o src/imagetreeitem.cpp

build/obj/licencedialog.o: src/licencedialog.cpp src/licencedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/licencedialog.o src/licencedialog.cpp

build/obj/main.o: src/main.cpp src/sgfile.h \
		src/mainwindow.h \
		src/sgimage.h \
		src/sgbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/sgfile.h \
		src/sgimage.h \
		src/sgbitmap.h \
		src/imagetreeitem.h \
		src/aboutdialog.h \
		src/licencedialog.h \
		src/gui/extractwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o src/mainwindow.cpp

build/obj/sgbitmap.o: src/sgbitmap.cpp src/sgbitmap.h \
		src/sgimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sgbitmap.o src/sgbitmap.cpp

build/obj/sgfile.o: src/sgfile.cpp src/sgfile.h \
		src/sgimage.h \
		src/sgbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sgfile.o src/sgfile.cpp

build/obj/sgimage.o: src/sgimage.cpp src/sgimage.h \
		src/sgbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sgimage.o src/sgimage.cpp

build/obj/filelistpage.o: src/gui/filelistpage.cpp src/gui/filelistpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filelistpage.o src/gui/filelistpage.cpp

build/obj/inputdirpage.o: src/gui/inputdirpage.cpp src/gui/inputdirpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/inputdirpage.o src/gui/inputdirpage.cpp

build/obj/outputdirpage.o: src/gui/outputdirpage.cpp src/gui/outputdirpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/outputdirpage.o src/gui/outputdirpage.cpp

build/obj/progresspage.o: src/gui/progresspage.cpp src/gui/progresspage.h \
		src/gui/extractthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/progresspage.o src/gui/progresspage.cpp

build/obj/extractthread.o: src/gui/extractthread.cpp src/gui/extractthread.h \
		src/sgfile.h \
		src/sgbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/extractthread.o src/gui/extractthread.cpp

build/obj/extractwizard.o: src/gui/extractwizard.cpp src/gui/extractwizard.h \
		src/gui/inputdirpage.h \
		src/gui/filelistpage.h \
		src/gui/outputdirpage.h \
		src/gui/progresspage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/extractwizard.o src/gui/extractwizard.cpp

build/obj/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/moc/moc_mainwindow.cpp

build/obj/moc_inputdirpage.o: build/moc/moc_inputdirpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_inputdirpage.o build/moc/moc_inputdirpage.cpp

build/obj/moc_outputdirpage.o: build/moc/moc_outputdirpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_outputdirpage.o build/moc/moc_outputdirpage.cpp

build/obj/moc_progresspage.o: build/moc/moc_progresspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_progresspage.o build/moc/moc_progresspage.cpp

build/obj/moc_extractthread.o: build/moc/moc_extractthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_extractthread.o build/moc/moc_extractthread.cpp

build/obj/moc_extractwizard.o: build/moc/moc_extractwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_extractwizard.o build/moc/moc_extractwizard.cpp

build/obj/qrc_sgreader.o: build/rcc/qrc_sgreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_sgreader.o build/rcc/qrc_sgreader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

